name: "WebAppIO-Webhook"
description: "Manually start a pipeline in WebAppIO"
inputs:
  apiKey:
    description: "API Key"
    required: true
  repoName:
    description: "repository name"
    required: true
  apiExtra:
    description: :'some extra data exposed as API_EXTRA variable'
    required: true
  buttons:
    description: "whether to automatically accept any BUTTON instructions in the job"
    required: true
  branch:
    description: "branch"
    required: true
  ref:
    description: "SHA of commit to checkout"
    required: true
runs:
  using: "node12"
  main: "index.js"
